export const styles = {
  container: {
    padding: 24,
    flexGrow: 1,
    backgroundColor: '#F3F4F6', // Hafif, modern bir gri arkaplan
  },
  card: {
    backgroundColor: '#FFFFFF',
    padding: 24,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 24,
    marginTop: 10,
    textAlign: 'center',
    color: '#1F2937',
  },
  input: {
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginBottom: 16,
    borderRadius: 10,
    fontSize: 16,
    color: '#374151',
  },
  label: {
    fontWeight: '700',
    marginBottom: 8,
    color: '#6B7280',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  resultContainer: {
    marginTop: 15,
    padding: 20,
    backgroundColor: '#ECFDF5', 
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  resultText: {
    fontSize: 15,
    color: '#065F46',
    marginBottom: 15,
    fontFamily: 'monospace', 
    padding: 12,
    backgroundColor: '#D1FAE5',
    borderRadius: 8,
    overflow: 'hidden',
  },
  text: {
    marginBottom: 10,
  },
  button: {
    backgroundColor: '#3B82F6',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  buttonSuccess: {
    backgroundColor: '#10B981',
    shadowColor: '#10B981',
  },
  buttonDanger: {
    backgroundColor: '#EF4444',
    shadowColor: '#EF4444',
  },
  buttonWarning: {
    backgroundColor: '#F59E0B',
    shadowColor: '#F59E0B',
  },
  buttonSecondary: {
    backgroundColor: '#6366F1',
    shadowColor: '#6366F1',
  },
  infoBox: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#3B82F6',
  },
  infoTitle: {
    fontWeight: 'bold',
    color: '#1E3A8A',
    marginBottom: 8,
    fontSize: 16,
  },
  infoText: {
    color: '#1E3A8A',
    lineHeight: 22,
  }
};
